services:
  sirf-mri-recon:
    build: . # Use the Dockerfile in the current directory
    container_name: compose-sirf-mri-recon
    user: "1000:1000" # Set the user to match the host user (replace with your UID:GID)
    group_add: [users] 
    ports:
      - "8888:8888"
    volumes:
      - /home/ubuntu/workdir:/home/jovyan/work
      - /mnt/share-private/materials:/mnt/materials
      - /mnt/share-private/SyneRBI/Project5:/input
      - /home/ubuntu/workdir/recons:/output
    # deploy: { resources: { reservations: { devices: [ {driver: nvidia, count: all, capabilities: [gpu] } ] } } }
    stdin_open: true
    tty: true
